name: 🖍️ Incorrect Documentation Report
description: Something is wrong or missing within the Docs.
labels:
  - 'bug:unverified'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping to improve the Developer Documentation!

        ## Tell us what's missing!

  - type: input
    attributes:
      label: What is the link to the documentation needing updated?
    validations:
      required: true
  - type: textarea
    attributes:
      label: What needs to be documented?
      description: A concise description of what you expected to see here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is currently documented?
      description: A concise description of what you're actually seeing.
    validations:
      required: true
