blank_issues_enabled: false
contact_links:
  - name: Get BigCommerce help
    url: https://support.bigcommerce.com/s/contact
    about:
      If you need to file a BigCommerce bug report our platform outage, utilize our traditional Support Team. Partners, please use your Partner Portal to open a case. 
  - name: Documentation + DevCenter Feature Request
    url: https://github.com/BigCommerce/Docs/discussions/new?category=ideas-feature-requests
    about:
      We appreciate you taking the time to improve our Documentation with your ideas! Meet us in Discussions to talk further about your feature request.
  - name: 💬 BigCommerce Community
    url: https://developer.bigcommerce.com/community
    about: Meet and chat with other people building on BigCommerce.
