openapi: '3.0.3'
info:
  title: Catalog - Brands
  termsOfService: 'https://www.bigcommerce.com/terms'
  contact:
    name: BigCommerce
    url: 'https://www.bigcommerce.com'
    email: support@bigcommerce.com
  version: ''
  description: |-
    > The Catalog API manages products, categories, brands, bulk pricing rules, and more. To learn more about catalog resources, see the [Catalog Overview](/api-docs/store-management/catalog/products-overview).
    
    Our Catalog Brands endpoints let you [create individual brands](/docs/rest-catalog/brands#create-a-brand) and [modify the brands](/docs/rest-catalog/brands#update-a-brand) associated with a store's products, along with [deleting brands](/docs/rest-catalog/brands#delete-a-brand). 
    
    Brand images have their own dedicated [create a brand image](/docs/rest-catalog/brands/images#create-a-brand-image) and [delete a brand image](/docs/rest-catalog/brands/images#delete-a-brand-image) endpoints. 
    
    In addition, brands have metafields that you can use to store information structured in key-value pairs; learn more about [creating brand metafields](/docs/rest-catalog/brands/metafields#create-a-brand-metafield), [updating brand metafields](/docs/rest-catalog/brands/metafields#update-a-brand-metafield), and [deleting brand metafields](/docs/rest-catalog/brands/metafields#delete-a-brand-metafield). 
    
    > To learn more about authenticating Catalog endpoints, locate the **Authentication** section at the top of each endpoint, then click **Show Details**. 
    
    ## Resources
    
    ### Webhooks
    * [Category](/api-docs/store-management/webhooks/events#category)
    
    ### Additional Catalog endpoints
    * [Categories](/docs/rest-catalog/categories)
    * [Category Trees](/docs/rest-catalog/category-trees)
    * [Products](/docs/rest-catalog/products)
    * [Product Modifiers](/docs/rest-catalog/product-modifiers)
    * [Product Variants](/docs/rest-catalog/product-variants)
    * [Product Variant Options](/docs/rest-catalog/product-variant-options)
servers:
  - url: 'https://api.bigcommerce.com/stores/{store_hash}/v3'
    variables:
      store_hash:
        default: store_hash
        description: Permanent ID of the BigCommerce store.
    description: BigCommerce API Gateway
security:
  - X-Auth-Token: []
tags:
  - name: Brands
  - name: Metafields
paths:
  '/catalog/brands/metafields':
    get:
      summary: Get All Metafields
      tags:
        - Metafields
      description: Get all brand metafields.
      operationId: getBrandMetafields
      responses:
        '200':
          description: |
            List of `Metafield` objects.
          content:
            application/json:
              schema:
                $ref: '__shared_models.yml#/components/schemas/MetaFieldCollectionResponse'
        '500':
          description: Internal Server Error
      parameters:
        - $ref: '__shared_models.yml#/components/parameters/PageParam'
        - $ref: '__shared_models.yml#/components/parameters/LimitParam'
        - $ref: '__shared_models.yml#/components/parameters/MetafieldKeyParam'
        - $ref: '__shared_models.yml#/components/parameters/MetafieldKeyInParam'
        - $ref: '__shared_models.yml#/components/parameters/MetafieldNamespaceParam'
        - $ref: '__shared_models.yml#/components/parameters/MetafieldNamespaceInParam'
        - $ref: '__shared_models.yml#/components/parameters/DirectionParam'
    post:
      summary: Create multiple Metafields
      tags:
        - Metafields
      description: Create multiple metafields.
      operationId: createBrandMetafields
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '__shared_models.yml#/components/schemas/MetafieldPost'
        description: ''
      responses:
        '200':
          description: |
            List of created `Metafield` objects. # TODO
          content:
            application/json:
              schema:
                $ref: '__shared_models.yml#/components/schemas/MetaFieldCollectionDeleteResponsePartialSuccess'
        '422':
          description: |
            Response object for metafields creation with partial success.
          content:
            application/json:
              schema:
                $ref: '__shared_models.yml#/components/schemas/MetaFieldCollectionResponse'
        '500':
          description: Internal Server Error
    put:
      summary: Update multiple Metafields
      tags:
        - Metafields
      description: Create multiple metafields.
      operationId: updateBrandMetafields
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '__shared_models.yml#/components/schemas/MetafieldPut'
        description: ''
      responses:
        '200':
          description: |
            List of updated `Metafield` objects.
          content:
            application/json:
              schema:
                $ref: '__shared_models.yml#/components/schemas/MetaFieldCollectionResponse'
        '422':
          description: |
            Response object for metafields creation with partial success.
          content:
            application/json:
              schema:
                $ref: '__shared_models.yml#/components/schemas/MetaFieldCollectionResponse'
        '500':
          description: Internal Server Error
    delete:
      summary: Delete All Metafields
      tags:
        - Metafields
      description: Delete all brand metafields.
      operationId: deleteBrandMetafields
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
        description: "Metafield's id list"
      responses:
        '200':
          description: |
            Response object for metafields deletion with success.
          content:
            application/json:
              schema:
                $ref: '__shared_models.yml#/components/schemas/MetaFieldCollectionDeleteResponseSuccess'
        '422':
          description: |
            Response object for metafields deletion with partial success.
          content:
            application/json:
              schema:
                $ref: '__shared_models.yml#/components/schemas/MetaFieldCollectionDeleteResponsePartialSuccess'
components:
  securitySchemes:
    X-Auth-Token:
      name: X-Auth-Token
      description: |-
        ### OAuth scopes

        | UI Name | Permission | Parameter |
        |:--------|:-----------|:----------|
        |  Products | modify | `store_v2_products` |
        |  Products | read-only | `store_v2_products_read_only` |

        ### Authentication header

        | Header | Argument | Description |
        |:-------|:---------|:------------|
        | `X-Auth-Token` | `access_token` | For more about API accounts that generate `access_token`s, see our [Guide to API Accounts](/api-docs/getting-started/api-accounts). |

        ### Further reading

        For example requests and more information about authenticating BigCommerce APIs, see [Authentication and Example Requests](/api-docs/getting-started/authentication#x-auth-token-header-example-requests).

        For more about BigCommerce OAuth scopes, see our [Guide to API Accounts](/api-docs/getting-started/api-accounts#oauth-scopes).

        For a list of API status codes, see [API Status Codes](/api-docs/getting-started/api-status-codes).
      type: apiKey
      in: header